//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 1/31/2020 08:38:45
namespace MyWaveProject
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Scenes
        {
            
            /// <summary> Asset Path (Scenes/MyScene.wescene.wesc) </summary>
            public static readonly Guid MyScene_wescene = new Guid("8dd8c85c-8015-4f38-b6c5-c88bd83290cc");
        }
        
        public sealed class Effects
        {
            
            /// <summary> Asset Path (Effects/LineBatchEffect.wefx) </summary>
            public static readonly Guid LineBatchEffect = new Guid("dcb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/LineEffect.wefx) </summary>
            public static readonly Guid LineEffect = new Guid("ddb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/SpriteBatchEffect.wefx) </summary>
            public static readonly Guid SpriteBatchEffect = new Guid("deb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/StandardEffect.wefx) </summary>
            public static readonly Guid StandardEffect = new Guid("daa1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/BillboardEffect.wefx) </summary>
            public static readonly Guid BillboardEffect = new Guid("dbb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
        }
        
        public sealed class Textures
        {
            
            /// <summary> Asset Path (Textures/dfgLut.png.wetx) </summary>
            public static readonly Guid dfgLut_png = new Guid("d81d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/Checker.png.wetx) </summary>
            public static readonly Guid Checker_png = new Guid("8b1d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/venice_sunset_16k_ibl.ktx.wetx) </summary>
            public static readonly Guid venice_sunset_16k_ibl_ktx = new Guid("df03a57c-8730-4db9-97c5-92e0afc77206");
        }
        
        public sealed class Models
        {
            
            /// <summary> Asset Path (Models/scene.bin.wefile) </summary>
            public static readonly Guid scene_bin = new Guid("dbb9ec5b-0323-41e0-b82e-6e84cf728281");
            
            /// <summary> Asset Path (Models/scene.gltf.wemd) </summary>
            public static readonly Guid scene_gltf = new Guid("85a3c9d8-a488-4cf3-a3b9-7b63890abe7a");
            
            public sealed class bullet
            {
                
                /// <summary> Asset Path (Models/bullet/scene.bin.wefile) </summary>
                public static readonly Guid scene_bin = new Guid("adca890f-778b-457a-ac5e-c7bed2019766");
                
                /// <summary> Asset Path (Models/bullet/scene.gltf.wemd) </summary>
                public static readonly Guid scene_gltf = new Guid("7d5b6570-5f5e-45fb-92a1-a753941116a3");
                
                public sealed class textures
                {
                    
                    /// <summary> Asset Path (Models/bullet/textures/lambert1_metallicRoughness.png.wetx) </summary>
                    public static readonly Guid lambert1_metallicRoughness_png = new Guid("28d85ebd-87fa-4397-8406-c33f6103853a");
                    
                    /// <summary> Asset Path (Models/bullet/textures/lambert1_baseColor.png.wetx) </summary>
                    public static readonly Guid lambert1_baseColor_png = new Guid("3927ae5a-4b3c-40cd-b2a1-b52a0fdc4600");
                }
                
                public sealed class scene_Embedded
                {
                    
                    public sealed class Samplers
                    {
                        
                        /// <summary> Asset Path (Models/bullet/scene_Embedded/Samplers/Sampler0.wesp) </summary>
                        public static readonly Guid Sampler0 = new Guid("d562d0d8-b8ae-4068-b578-5918adf63577");
                    }
                    
                    public sealed class Materials
                    {
                        
                        /// <summary> Asset Path (Models/bullet/scene_Embedded/Materials/lambert1.wemt) </summary>
                        public static readonly Guid lambert1 = new Guid("bee322ac-1591-42cc-80bd-c4ed2212c5d4");
                    }
                }
            }
            
            public sealed class textures
            {
                
                /// <summary> Asset Path (Models/textures/body_baseColor.png.wetx) </summary>
                public static readonly Guid body_baseColor_png = new Guid("85831b8d-f3f2-46c2-88b5-3695e68b3ec4");
                
                /// <summary> Asset Path (Models/textures/material_metallicRoughness.png.wetx) </summary>
                public static readonly Guid material_metallicRoughness_png = new Guid("42f8e229-4efa-4626-ab30-590a8d43c99e");
                
                /// <summary> Asset Path (Models/textures/body_emissive.png.wetx) </summary>
                public static readonly Guid body_emissive_png = new Guid("8f893b4e-731c-4174-a5d2-f4bcfefc5827");
                
                /// <summary> Asset Path (Models/textures/material_baseColor.png.wetx) </summary>
                public static readonly Guid material_baseColor_png = new Guid("01b79e0d-dca6-4f3d-b4f6-7b3aa2b91df0");
                
                /// <summary> Asset Path (Models/textures/body_metallicRoughness.png.wetx) </summary>
                public static readonly Guid body_metallicRoughness_png = new Guid("c4830f59-0c2a-4580-b5a7-89f8d4855000");
                
                /// <summary> Asset Path (Models/textures/material_normal.png.wetx) </summary>
                public static readonly Guid material_normal_png = new Guid("e7e93e99-3594-4431-8614-dbc10fc35c0e");
                
                /// <summary> Asset Path (Models/textures/Boden_metallicRoughness.png.wetx) </summary>
                public static readonly Guid Boden_metallicRoughness_png = new Guid("0d8e6e82-3677-4c57-8924-821cfbc7da98");
                
                /// <summary> Asset Path (Models/textures/Boden_normal.png.wetx) </summary>
                public static readonly Guid Boden_normal_png = new Guid("9aaf6233-99af-4914-a141-f95cad903ad6");
                
                /// <summary> Asset Path (Models/textures/body_normal.png.wetx) </summary>
                public static readonly Guid body_normal_png = new Guid("463320a7-82b8-4017-b493-6e17c0107366");
                
                /// <summary> Asset Path (Models/textures/Boden_baseColor.png.wetx) </summary>
                public static readonly Guid Boden_baseColor_png = new Guid("07fe8de6-ff74-4162-99c7-be08b7831d5a");
            }
            
            public sealed class road
            {
                
                /// <summary> Asset Path (Models/road/scene.bin.wefile) </summary>
                public static readonly Guid scene_bin = new Guid("46a6d4ab-3073-43e0-815f-fd418a53397e");
                
                /// <summary> Asset Path (Models/road/scene.gltf.wemd) </summary>
                public static readonly Guid scene_gltf = new Guid("18dd4ce1-eea4-4528-899e-435d1d033720");
                
                public sealed class textures
                {
                    
                    /// <summary> Asset Path (Models/road/textures/track_1_normal.png.wetx) </summary>
                    public static readonly Guid track_1_normal_png = new Guid("3c2adc11-354a-44c4-9491-eb318fda77a2");
                    
                    /// <summary> Asset Path (Models/road/textures/track_1_baseColor.png.wetx) </summary>
                    public static readonly Guid track_1_baseColor_png = new Guid("038d0e1a-6216-484f-8ca7-34c1f7123386");
                    
                    /// <summary> Asset Path (Models/road/textures/track_1_metallicRoughness.png.wetx) </summary>
                    public static readonly Guid track_1_metallicRoughness_png = new Guid("792ebc37-b103-407d-b9b2-5cff8ae7bd1d");
                }
                
                public sealed class scene_Embedded
                {
                    
                    public sealed class Samplers
                    {
                        
                        /// <summary> Asset Path (Models/road/scene_Embedded/Samplers/Sampler0.wesp) </summary>
                        public static readonly Guid Sampler0 = new Guid("d9f26d50-d027-4ef2-a559-97b212d56ce9");
                    }
                    
                    public sealed class Materials
                    {
                        
                        /// <summary> Asset Path (Models/road/scene_Embedded/Materials/track_1.wemt) </summary>
                        public static readonly Guid track_1 = new Guid("5dfc810a-2252-4b92-96ec-41977c689e75");
                    }
                }
            }
            
            public sealed class scene_Embedded
            {
                
                public sealed class Samplers
                {
                    
                    /// <summary> Asset Path (Models/scene_Embedded/Samplers/Sampler0.wesp) </summary>
                    public static readonly Guid Sampler0 = new Guid("765a335a-2900-4773-b6a3-8cc1536cbf46");
                }
                
                public sealed class Materials
                {
                    
                    /// <summary> Asset Path (Models/scene_Embedded/Materials/body.wemt) </summary>
                    public static readonly Guid body = new Guid("619236ec-725e-4e2c-a649-5ec5538681ca");
                    
                    /// <summary> Asset Path (Models/scene_Embedded/Materials/material.wemt) </summary>
                    public static readonly Guid material = new Guid("aefe8498-8535-451b-9207-413be6fac97a");
                    
                    /// <summary> Asset Path (Models/scene_Embedded/Materials/Boden.wemt) </summary>
                    public static readonly Guid Boden = new Guid("a262dd4e-60ca-42e7-a5d0-479186ba0dbd");
                }
            }
        }
        
        public sealed class Samplers
        {
            
            /// <summary> Asset Path (Samplers/LinearClampSampler.wesp) </summary>
            public static readonly Guid LinearClampSampler = new Guid("7d1e2792-2031-42bb-a67c-0dbd282be12a");
            
            /// <summary> Asset Path (Samplers/LinearWrapSampler.wesp) </summary>
            public static readonly Guid LinearWrapSampler = new Guid("9018edf8-ea96-4721-bf83-5561942432e0");
        }
        
        public sealed class Materials
        {
            
            /// <summary> Asset Path (Materials/DefaultMaterial.wemt) </summary>
            public static readonly Guid DefaultMaterial = new Guid("02181b63-5a0e-46d1-9208-d92376ae33fb");
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary> Asset Path (RenderLayers/Alpha.werl) </summary>
            public static readonly Guid Alpha = new Guid("e35c59a9-26ab-4b4c-8210-4b1f21c31530");
            
            /// <summary> Asset Path (RenderLayers/Opaque.werl) </summary>
            public static readonly Guid Opaque = new Guid("0db59561-b3f5-444f-b5de-e62e3a5b42bf");
        }
    }
}
